# Generated by Django 6.0.1 on 2026-08-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='poster_path',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='release_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='media',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='tmdb_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
