# Generated by Django 6.0.1 on 2026-08-17 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_media_genre_media_overview_media_poster_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='poster_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', False)), fields=('owner', 'tmdb_id'), name='unique_user_tmdb_media'),
        ),
    ]
